// Start the local server before running this smoke test. TEST_URL may be file://.../web/index.html.
const {chromium} = require('playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
(async()=>{
 const browser=await chromium.launch({headless:true, ...(process.env.CHROMIUM_PATH ? {executablePath:process.env.CHROMIUM_PATH} : {})});
 const page=await browser.newPage({viewport:{width:1440,height:1040}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const base=process.env.TEST_URL||'http://127.0.0.1:8765';
 await page.goto(base);await page.waitForSelector('h1');
 assert.match(await page.locator('main h1').innerText(),/customer words/);
 await page.screenshot({path:'docs/assets/overview.png',fullPage:true});
 await page.click('[data-view="signals"]');
 assert.ok(await page.locator('[data-alert]').count()>0);
 await page.locator('[data-alert]').first().click();await page.waitForSelector('dialog[open]');
 await page.click('#close-detail');
 await page.screenshot({path:'docs/assets/signals.png',fullPage:true});
 await page.click('[data-view="explorer"]');
 await page.fill('#search','zznotfoundzz');await page.click('#search-button');
 await page.waitForFunction(()=>document.querySelector('#record-table').textContent.includes('No matches'));
 await page.fill('#search','');await page.click('#search-button');
 await page.waitForSelector('[data-record]');await page.locator('[data-record]').first().click();
 await page.waitForSelector('dialog[open]');await page.click('#close-detail');
 await page.click('[data-view="topics"]');
 assert.equal(await page.locator('.topic-card').count(),8);
 await page.locator('.topic-example').first().click();await page.waitForSelector('dialog[open]');await page.click('#close-detail');
 await page.click('[data-view="models"]');await page.click('#classify');
 assert.equal(await page.locator('.result-card').count(),2);
 await page.screenshot({path:'docs/assets/model-lab.png',fullPage:true});
 await page.fill('#complaint-text','tiny');await page.click('#classify');
 assert.ok(await page.locator('#classification .error').count());
 await page.click('[data-view="evidence"]');
 assert.match(await page.locator('main h1').innerText(),/Follow the data/);
 await page.setViewportSize({width:390,height:844});await page.click('[data-view="overview"]');
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 await page.screenshot({path:'docs/assets/mobile.png',fullPage:true});
 assert.deepEqual(errors,[]);
 await browser.close();console.log('Browser smoke passed: six views, filtering, dialogs, inference and mobile width.');
})().catch(error=>{console.error(error);process.exit(1);});
