'use strict';
const R = window.REPORT;
const $ = s => document.querySelector(s);
const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt = n => Number(n).toLocaleString('en-US');
const pct = n => (100 * n).toFixed(1) + '%';
const short = p => R.scope.products[p] || p;
const colors = ['#247869','#8eac72','#6e8cac'];
const products = Object.keys(R.scope.products);
const state = {view:'overview', page:0, records:R.records.slice().reverse(), searchTotal:R.records.length, local:false};
const el = (tag, cls, text) => { const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n; };
function pageHead(kicker,title,desc,button='') {return `<div class="page-head"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1><p>${desc}</p></div>${button}</div>`;}
function stat(label,value,note,emphasis=false){return `<div class="stat ${emphasis?'emphasis':''}"><div class="label">${label}</div><div class="value">${value}</div><div class="note">${note}</div></div>`;}
function chart(rows, keys, palette=colors, expected=false){
  const width=700,height=230,pad={left:40,right:10,top:16,bottom:30};
  const max=Math.max(...rows.flatMap(r=>keys.map(k=>Number(r[k])||0)),1)*1.15;
  const x=i=>pad.left+i*(width-pad.left-pad.right)/Math.max(rows.length-1,1);
  const y=v=>height-pad.bottom-v/max*(height-pad.top-pad.bottom);
  let svg=`<svg class="chart" viewBox="0 0 ${width} ${height}" role="img" aria-label="Weekly time series from January through December 2024">`;
  for(let i=0;i<4;i++){const val=max*i/3;svg+=`<line class="gridline" x1="40" x2="690" y1="${y(val)}" y2="${y(val)}"/><text x="30" y="${y(val)+4}" text-anchor="end">${Math.round(val)}</text>`;}
  keys.forEach((key,j)=>{
    const points=rows.map((r,i)=>r[key]===null?null:[x(i),y(Number(r[key])||0)]).filter(Boolean);
    if(!points.length)return;
    const d='M'+points.map(p=>p.join(',')).join(' L');
    if(j===0&&!expected)svg+=`<path d="${d} L${x(rows.length-1)},${height-pad.bottom} L${x(0)},${height-pad.bottom} Z" fill="${palette[j]}" opacity=".06"/>`;
    svg+=`<path class="line" d="${d}" stroke="${palette[j]}" ${j===1&&expected?'stroke-dasharray="5 5"':''}/>`;
    if(expected&&j===0)rows.forEach((r,i)=>{if(r.alert)svg+=`<circle cx="${x(i)}" cy="${y(r[key])}" r="5" fill="#c36832"><title>${escape(r.week)}: ${r.observed} complaints, ${r.lift}× baseline</title></circle>`;});
  });
  [0,8,17,26,35,43,51].filter(i=>i<rows.length).forEach(i=>svg+=`<text x="${x(i)}" y="224" text-anchor="${i===0?'start':i===rows.length-1?'end':'middle'}">${new Date(rows[i].week+'T00:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'})}</text>`);
  return svg+'</svg>';
}
function alertRows(alerts, limit=100){return alerts.slice(0,limit).map(a=>`<tr data-alert="${escape(a.id)}" tabindex="0"><td><div class="cell-title">${escape(a.issue)}</div><div class="cell-sub">${escape(short(a.product))} · ${a.id}</div></td><td class="numeric">${a.week}</td><td class="numeric">${a.observed}<div class="cell-sub">baseline ${a.expected.toFixed(1)}</div></td><td class="number-up">${a.lift.toFixed(1)}×</td><td><span class="badge ${a.severity==='High'?'warn':'neutral'}">${a.severity}</span></td></tr>`).join('') || '<tr class="empty-row"><td colspan="5">No alerts meet the selected policy.</td></tr>';}
function alertsTable(alerts,limit){return `<div class="table-wrap"><table><thead><tr><th>Product / issue</th><th>Week of</th><th>Observed</th><th>Lift</th><th>Priority</th></tr></thead><tbody>${alertRows(alerts,limit)}</tbody></table></div>`;}
function download(name,rows){
  if(!rows.length)return;
  const keys=Object.keys(rows[0]);
  const quote=v=>{let s=String(v??'');if(/^[\s]*[=+\-@]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};
  const csv=[keys.map(quote).join(','),...rows.map(r=>keys.map(k=>quote(r[k])).join(','))].join('\r\n');
  const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));
  const link=el('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
function overview(){
 const totals=products.map(p=>R.matrix.filter(x=>x.product===p).reduce((s,x)=>s+x.count,0));
 const metrics=R.models.issue.test;
 $('#main').innerHTML=pageHead('01 / Portfolio overview','From customer words to signals.','Explore complaint patterns, investigate unusual weeks, and inspect the evidence behind each model.','<button class="button" id="export-weekly">↓ Export weekly data</button>')+
 `<div class="stats">${stat('Complaints in scope',fmt(R.summary.complaints),'3 product groups · 52 complete weeks')}${stat('Published narratives',fmt(R.summary.narratives),pct(R.summary.narratives/R.summary.complaints)+' of this cohort')}${stat('Historical review signals',fmt(R.summary.alerts),'Jul–Dec 2024 · '+R.alert_policy.series+' monitored series',true)}${stat('Issue classifier · macro-F1',metrics.macro_f1.toFixed(3),'Held-out Q4 · majority baseline '+metrics.majority_baseline_macro_f1.toFixed(3))}</div>`+
 `<div class="grid"><section class="panel"><div class="panel-head"><div><h2>Weekly complaint volume</h2><p class="subtle">All records, including those without a narrative</p></div><span class="badge neutral">52 WEEKS</span></div><div class="panel-body"><div class="legend">${Object.values(R.scope.products).map((p,i)=>`<span><i style="background:${colors[i]}"></i>${p}</span>`).join('')}</div>${chart(R.weekly,Object.values(R.scope.products))}</div><div class="panel-note">Received-date view · current metadata joined with the official narrative archive</div></section>
 <section class="panel"><div class="panel-head"><div><h2>Product mix</h2><p class="subtle">Share of complaints in this cohort</p></div></div><div class="panel-body">${products.map((p,i)=>`<div class="product-row"><div class="row"><span>${short(p)}</span><strong>${fmt(totals[i])}</strong></div><div class="track"><span style="width:${totals[i]/R.summary.complaints*100}%;background:${colors[i]}"></span></div><div class="cell-sub">${pct(totals[i]/R.summary.complaints)} of records</div></div>`).join('')}</div><div class="insight">Volumes reflect reporting behavior and exposure. They are not measures of product failure rates.</div></section></div>`+
 `<section class="panel"><div class="panel-head"><div><h2>Signals to investigate</h2><p class="subtle">Highest standardized deviations in July–December 2024</p></div><button class="title-link" id="all-signals">View all signals →</button></div>${alertsTable(R.alerts,4)}</section>`;
 $('#export-weekly').onclick=()=>download('weekly-counts.csv',R.weekly);$('#all-signals').onclick=()=>navigate('signals'); bindAlerts();
}
function signals(){
 const pairs=[...new Set(R.series.map(x=>x.product+'||'+x.issue))];
 const initial=R.alerts[0] ? R.alerts[0].product+'||'+R.alerts[0].issue:pairs[0];
 $('#main').innerHTML=pageHead('02 / Statistical monitoring','Look closer at unusual weeks.','Past-only, 12-week baselines with overdispersion and a weekly multiple-testing correction.','<button class="button" id="export-alerts">↓ Export signals</button>')+
 `<div class="stats">${stat('Flagged series-weeks',R.alerts.length,'Investigation leads · not verified incidents',true)}${stat('Series monitored',R.alert_policy.series,'Product × issue, fixed on training data')}${stat('Synthetic null flag rate',pct(R.simulation.null_flag_rate),fmt(R.simulation.null_series_weeks)+' simulated series-weeks')}${stat('Injected surge detection',pct(R.simulation.injected_detection_rate),'Four-week, expected 4× surge simulation')}</div>
 <section class="panel"><div class="panel-head"><div><h2>Observed versus expected</h2><p class="subtle">Orange dots show weeks passing every alert gate</p></div><select id="series-select" aria-label="Select monitored series">${pairs.map(p=>`<option value="${escape(p)}" ${p===initial?'selected':''}>${escape(short(p.split('||')[0])+' · '+p.split('||')[1])}</option>`).join('')}</select></div><div class="panel-body"><div class="legend"><span><i style="background:#247869"></i>Observed</span><span><i style="background:#8eac72"></i>Expected</span><span><i style="background:#c36832"></i>Review signal</span></div><div id="signal-chart"></div></div><div class="panel-note">January–June defines the monitoring family; flags start in July. CUSUM shift watches are exploratory and are not added to the alert count.</div></section>
 <div class="callout">Alert policy: adjusted tail score ≤ 0.05 · at least 5 complaints · at least 1.5× baseline · standardized deviation ≥ 3. Predictive tails use estimated parameters; error control is approximate.</div>
 <section class="panel"><div class="panel-head"><h2>Historical signal register</h2><span class="badge neutral">HUMAN REVIEW</span></div>${alertsTable(R.alerts)}</section>`;
 const draw=()=>{const [product,issue]=$('#series-select').value.split('||');$('#signal-chart').innerHTML=chart(R.series.filter(x=>x.product===product&&x.issue===issue),['observed','expected'],colors,true);};draw();$('#series-select').onchange=draw;
 $('#export-alerts').onclick=()=>download('review-signals.csv',R.alerts);bindAlerts();
}
function bindAlerts(){document.querySelectorAll('[data-alert]').forEach(tr=>{const open=()=>{
 const a=R.alerts.find(x=>x.id===tr.dataset.alert);
 $('#detail-body').innerHTML=`<div class="eyebrow">${a.id} / ${escape(short(a.product))}</div><h1>${escape(a.issue)}</h1><p class="subtle">Week beginning ${a.week} · historical review signal</p><div class="detail-grid"><div><small>Observed complaints</small><strong>${a.observed}</strong></div><div><small>Trailing 12-week mean</small><strong>${a.expected.toFixed(2)}</strong></div><div><small>Volume / baseline</small><strong>${a.lift.toFixed(2)}×</strong></div><div><small>Adjusted tail score</small><strong>${a.q.toFixed(6)}</strong></div></div><h3>What to check</h3><p>Review the underlying complaint IDs and narratives for this product, issue and week. Check reporting bursts, repeated wording, policy changes and operational events before assigning an incident label.</p><p class="subtle">A statistical flag cannot establish its cause. The underlying source is a retrospective snapshot.</p>`;
 $('#detail').showModal();};tr.onclick=open;tr.onkeydown=e=>{if(e.key==='Enter')open();};});}
function explorer(){
 $('#main').innerHTML=pageHead('03 / Case exploration','Read the evidence behind the counts.','Search narratives and complaint metadata. Open a record to compare its reported issue with the model output.','<button class="button" id="export-records">↓ Export results</button>')+
 `<div class="toolbar"><input id="search" placeholder="Search text, company, issue or complaint ID…" aria-label="Search complaints"><select id="product-filter" aria-label="Filter by product"><option value="">All products</option>${products.map(p=>`<option value="${escape(p)}">${short(p)}</option>`).join('')}</select><button class="button primary" id="search-button">Search</button></div><p class="subtle" id="search-scope"></p><section class="panel"><div id="record-table"></div><div class="paging"><span id="page-label"></span><button class="button" id="prev-page">←</button><button class="button" id="next-page">→</button></div></section>
 <section class="panel" style="margin-top:22px"><div class="panel-head"><div><h2>Product × reported issue</h2><p class="subtle">Ten largest issues · entire cohort, unaffected by search</p></div></div><div class="table-wrap" id="heatmap"></div></section>`;
 state.page=0;state.records=R.records.slice().reverse();state.searchTotal=state.records.length;renderRecords();
 const search=async()=>{const q=$('#search').value.trim(),product=$('#product-filter').value;state.page=0;
  if(location.protocol!=='file:')try{const response=await fetch('/api/search?'+new URLSearchParams({q,product}));if(response.ok){const data=await response.json();state.records=data.records;state.searchTotal=data.total;state.local=true;renderRecords();return;}}catch(e){/* Static mode uses the embedded preview. */}
  state.local=false;state.records=R.records.slice().reverse().filter(r=>(!product||r.product===product)&&[r.id,r.company,r.issue,r.excerpt].join(' ').toLowerCase().includes(q.toLowerCase()));state.searchTotal=state.records.length;renderRecords();};
 $('#search-button').onclick=search;$('#search').onkeydown=e=>{if(e.key==='Enter')search();};$('#product-filter').onchange=search;
 $('#prev-page').onclick=()=>{if(state.page>0){state.page--;renderRecords();}};$('#next-page').onclick=()=>{if((state.page+1)*10<state.records.length){state.page++;renderRecords();}};
 $('#export-records').onclick=()=>download('complaint-search.csv',state.records);renderHeatmap();search();
}
function renderRecords(){
 const shown=state.records.slice(state.page*10,state.page*10+10);
 $('#search-scope').textContent=state.local?`${fmt(state.searchTotal)} matching records · newest ${Math.min(100,state.searchTotal)} available here. Full local search after fetching and building data.`:`Bundled preview: ${R.records.length} selected excerpts, not the full cohort. ${state.records.length} match your search. Run the local data build for full-text search.`;
 $('#record-table').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Complaint</th><th>Product / reported issue</th><th>Narrative excerpt</th><th>Model score</th></tr></thead><tbody>${shown.map(r=>`<tr data-record="${r.id}" tabindex="0"><td class="numeric">#${r.id}<div class="cell-sub">${r.date}</div></td><td><div class="cell-title">${escape(short(r.product))}</div><div class="cell-sub">${escape(r.issue)}</div></td><td style="max-width:420px"><div>${escape(r.excerpt?r.excerpt.slice(0,135)+'…':'No published narrative')}</div><div class="cell-sub">${escape(r.company)}</div></td><td><span class="badge ${r.confidence<R.models.issue.review_threshold?'warn':'neutral'}">${r.prediction?pct(r.confidence):'Not modeled'}</span></td></tr>`).join('')||'<tr class="empty-row"><td colspan="4">No matches. Try a broader term or another product.</td></tr>'}</tbody></table></div>`;
 $('#page-label').textContent=`${state.records.length?state.page+1:0} / ${Math.ceil(state.records.length/10)}`;$('#prev-page').disabled=state.page===0;$('#next-page').disabled=(state.page+1)*10>=state.records.length;
 document.querySelectorAll('[data-record]').forEach(tr=>{const open=()=>recordDetail(state.records.find(r=>r.id===tr.dataset.record));tr.onclick=open;tr.onkeydown=e=>{if(e.key==='Enter')open();};});
}
function recordDetail(r){
 $('#detail-body').innerHTML=`<div class="eyebrow">CFPB #${r.id} / ${r.date}</div><h1>${escape(short(r.product))}</h1><p>${escape(r.company)}</p><blockquote class="detail-quote">${escape(r.excerpt||'No public narrative is available for this record.')}</blockquote><p class="subtle">Short excerpt from the official archive. Consumer allegation, not an independently verified finding.</p><div class="detail-grid"><div><small>Consumer-selected issue</small>${escape(r.issue)}</div><div><small>Model suggestion</small>${escape(r.prediction||'Not modeled')}</div><div><small>Model score</small>${r.prediction?pct(r.confidence):'—'}</div><div><small>Evaluation partition</small>${escape(r.split)}</div></div><p class="subtle">The reported issue is a noisy label; a disagreement does not prove the consumer or model is wrong. Archived narrative text may no longer appear on the current CFPB site.</p><a href="https://www.consumerfinance.gov/data-research/consumer-complaints/search/detail/${r.id}" target="_blank" rel="noopener noreferrer">Open source complaint metadata ↗</a>`;
 $('#detail').showModal();
}
function renderHeatmap(){
 const totals={};R.matrix.forEach(x=>totals[x.issue]=(totals[x.issue]||0)+x.count);const issues=Object.keys(totals).sort((a,b)=>totals[b]-totals[a]).slice(0,10);const max=Math.max(...R.matrix.map(x=>x.count));
 $('#heatmap').innerHTML=`<table class="heatmap"><thead><tr><th>Reported issue</th>${products.map(p=>`<th>${short(p)}</th>`).join('')}</tr></thead><tbody>${issues.map(i=>`<tr><td>${escape(i)}</td>${products.map(p=>{const v=R.matrix.find(x=>x.product===p&&x.issue===i)?.count||0;return `<td style="background:rgba(42,119,97,${v/max*.25})">${v?fmt(v):'—'}</td>`;}).join('')}</tr>`).join('')}</tbody></table>`;
}
function topics(){
 $('#main').innerHTML=pageHead('04 / Unsupervised text analysis','Recurring themes, in customers’ words.','Eight NMF topics learned on training-period narratives, then applied to later records. Terms are automatic descriptions, not incident labels.')+
 `<div class="callout">Change compares narrative share in 2–29 December with 4 November–1 December. Small counts and self-selection can move topic shares; this is an exploratory view.</div><div class="topic-grid">${R.topics.map(t=>`<section class="panel topic-card"><div class="id">TOPIC ${String(t.id+1).padStart(2,'0')} / ${fmt(t.count)} NARRATIVES</div><h2>${escape(t.terms.slice(0,3).join(' · '))}</h2><div class="chips">${t.terms.map(term=>`<span class="chip">${escape(term)}</span>`).join('')}</div><div class="topic-footer"><span>${t.recent} recent / ${t.previous} prior</span><span class="badge ${t.share_change_pp>0?'warn':'neutral'}">${t.share_change_pp>0?'+':''}${t.share_change_pp.toFixed(1)} pp share</span></div><button class="title-link topic-example" data-topic="${t.id}">Read representative excerpts →</button></section>`).join('')}</div>`;
 document.querySelectorAll('.topic-example').forEach(button=>button.onclick=()=>{const t=R.topics.find(x=>x.id===Number(button.dataset.topic));const examples=t.examples.map(id=>R.records.find(r=>r.id===id)).filter(Boolean);$('#detail-body').innerHTML=`<div class="eyebrow">Topic ${t.id+1}</div><h1>${escape(t.terms.slice(0,3).join(' · '))}</h1><p class="subtle">Highest topic-weight examples; representative of the model, not a random sample.</p>${examples.map(r=>`<p class="subtle">#${r.id} · ${r.date} · ${escape(short(r.product))}</p><blockquote class="detail-quote">${escape(r.excerpt)}</blockquote>`).join('')}`;$('#detail').showModal();});
}
function models(){
 const m=R.models.issue,s=R.splits.split_counts;
 $('#main').innerHTML=pageHead('05 / Model evaluation','A suggestion you can inspect.','Test an English complaint locally, then compare the classifier against held-out results. No text leaves your browser.')+
 `<div class="grid equal"><section class="panel"><div class="panel-head"><h2>Try the text classifier</h2><span class="badge">LOCAL INFERENCE</span></div><div class="panel-body"><label for="complaint-text" class="subtle">Complaint narrative · English</label><textarea id="complaint-text" maxlength="12000" placeholder="Describe a banking issue in English…">I transferred money from my checking account last week. The payment was deducted but the recipient never received it. I contacted customer support several times and still have no explanation.</textarea><div class="row-actions" style="margin-top:14px"><button id="classify" class="button primary">Classify complaint →</button><span class="explanation">TF-IDF + logistic regression</span></div><div id="classification" aria-live="polite"></div></div></section>
 <section class="panel"><div class="panel-head"><div><h2>Issue classification · Q4 holdout</h2><p class="subtle">${fmt(m.test.rows)} unique narratives, 11 target classes</p></div><span class="badge neutral">OUT OF TIME</span></div><div class="panel-body">${metric('Macro-F1',m.test.macro_f1.toFixed(3))}${metric('95% bootstrap interval',m.test.macro_f1_bootstrap_95.map(x=>x.toFixed(3)).join(' — '))}${metric('Majority baseline · macro-F1',m.test.majority_baseline_macro_f1.toFixed(3))}${metric('Accuracy',pct(m.test.accuracy))}${metric('Multiclass Brier score',m.test.multiclass_brier.toFixed(3))}${metric('ECE · 10 confidence bins',m.test.ece_10_bins.toFixed(3))}${metric('Routing coverage at score ≥ '+m.review_threshold.toFixed(2),pct(m.test.routing_coverage))}${metric('Accuracy within routed subset',m.test.routing_accuracy===null?'No accepted predictions':pct(m.test.routing_accuracy))}</div><div class="panel-note">Scores are uncalibrated. Threshold chosen on validation data; “routed” still means a human-review suggestion.</div></section></div>
 <section class="panel"><div class="panel-head"><h2>Time moves in one direction</h2><span class="badge neutral">NO RANDOM TRAIN / TEST SPLIT</span></div><div class="panel-body"><div class="split-bar"><span style="width:50%;background:#247869">TRAIN · JAN–JUN</span><span style="width:25%;background:#7d9b6f">VALIDATE · JUL–SEP</span><span style="width:25%;background:#6986a0">TEST · Q4</span></div><div class="legend"><span>${fmt(s.train)} train</span><span>${fmt(s.validation)} validation</span><span>${fmt(s.test)} test</span><span>${fmt(R.splits.duplicates_removed)} normalized duplicates removed</span></div><p class="subtle">Vocabulary, topic components and the ten most frequent issue labels are learned on training data. C and routing thresholds use validation only. Test results do not select a model.</p></div></section>
 <div class="grid equal" style="margin-top:22px"><section class="panel"><div class="panel-head"><h2>Per-class issue performance</h2></div><div class="table-wrap"><table><thead><tr><th>Class</th><th>Precision</th><th>Recall</th><th>F1</th><th>n</th></tr></thead><tbody>${m.classes.map(c=>{const r=m.test.per_class[c];return `<tr><td>${escape(c)}</td><td>${r.precision.toFixed(2)}</td><td>${r.recall.toFixed(2)}</td><td>${r['f1-score'].toFixed(2)}</td><td>${r.support}</td></tr>`;}).join('')}</tbody></table></div></section><section class="panel"><div class="panel-head"><h2>Product classification</h2></div><div class="panel-body">${metric('Test macro-F1',R.models.product.test.macro_f1.toFixed(3))}${metric('Test accuracy',pct(R.models.product.test.accuracy))}${metric('Majority baseline',R.models.product.test.majority_baseline_macro_f1.toFixed(3))}<div class="callout">Product labels are broader and easier to infer from text than the issue taxonomy. Compare both tasks rather than reporting only the stronger score.</div><h3>What this model cannot tell you</h3><ul class="notes-list"><li>Whether a complaint is true or a violation occurred.</li><li>Whether the model transfers to Turkish banking language.</li><li>Whether a topic is genuinely new outside this cohort.</li><li>How it performs on records without a published narrative.</li></ul></div></section></div>`;
 $('#classify').onclick=()=>{try{const result=window.ComplaintModel.classify(window.MODEL,$('#complaint-text').value);$('#classification').innerHTML=Object.entries(result).map(([target,r])=>`<div class="result-card"><div class="row-actions"><span class="eyebrow">${target} suggestion</span><span class="badge ${r.review?'warn':'neutral'}">${r.review?'LOW SCORE · REVIEW':'REVIEW SUGGESTION'}</span></div><h3>${escape(target==='product'?short(r.label):r.label)}</h3><p class="subtle">Model score ${pct(r.confidence)} · not a calibrated probability</p><div class="chips">${r.top_terms.map(t=>`<span class="chip" title="Logit contribution: ${t.contribution.toFixed(3)}">${escape(t.term)}</span>`).join('')}</div><p class="explanation">Terms contributing positively to the selected class score; not causal explanations.</p></div>`).join('');}catch(error){$('#classification').innerHTML=`<p class="error">${escape(error.message)}</p>`;}};
}
function metric(label,value){return `<div class="metric-row"><span>${label}</span><strong>${value}</strong></div>`;}
function evidence(){
 $('#main').innerHTML=pageHead('06 / Reproducibility','Follow the data. Question the result.','Source files, cohort boundaries and modeling decisions are documented so the analysis can be rebuilt and challenged.','<button class="button" id="print-report">Print this view</button>')+
 `<div class="grid equal"><section class="panel"><div class="panel-head"><h2>Where the data comes from</h2></div><div class="panel-body"><p>Current CFPB complaint metadata is joined by complaint ID to four official historical narrative archives.</p><div class="callout">CFPB removed narratives from its live database in September 2026. The text model uses the official FOIA archive; it is not connected to a live narrative feed.</div>${metric('Geography','New York, USA')}${metric('Received-date cohort','01 Jan — 29 Dec 2024')}${metric('Metadata records',fmt(R.summary.complaints))}${metric('Narratives available',fmt(R.summary.narratives))}${metric('Archive ID matches',fmt(R.source.archive_id_matches||0))}<p class="subtle">${escape(R.source.as_of_caution||'User-supplied CSV cohort')}</p></div></section>
 <section class="panel"><div class="panel-head"><h2>Build and inspect</h2></div><div class="panel-body"><pre>python -m pip install -r requirements.txt
python -m complaint_intelligence fetch
python -m complaint_intelligence build
python -m complaint_intelligence validate
python -m unittest discover -s tests -v</pre><p class="subtle">The first download is approximately 290 MB. Raw records stay local. The bundled workbench opens without Python.</p><div class="row-actions"><button class="button" id="export-matrix">Export product–issue matrix</button><button class="button" id="export-topics">Export topics</button></div></div></section></div>
 <section class="panel"><div class="panel-head"><h2>Interpretation boundaries</h2></div><div class="panel-body"><ul class="notes-list">${R.cautions.map(c=>`<li>${escape(c)}</li>`).join('')}<li>Exact normalized duplicates are removed for modeling. Similar templates may remain.</li><li>Bootstrap intervals describe resampling variability, not future deployment performance.</li><li>New product–issue pairs outside the training-defined monitoring family are not automatically alerted.</li></ul></div></section>
 <section class="panel" style="margin-top:22px"><div class="panel-head"><h2>Source manifest</h2><span class="badge neutral">SHA-256</span></div><div class="panel-body source-list">${(R.source.sources||[]).map(s=>`<p><a href="${escape(s.url)}" target="_blank" rel="noopener noreferrer">${escape(s.url.split('/').pop().startsWith('?')?'CFPB filtered metadata export':s.url.split('/').pop())}</a><br><span class="mono">${escape(s.sha256)}</span></p>`).join('')}<p class="subtle">Built with Python ${R.runtime.python}, pandas ${R.runtime.pandas}, scikit-learn ${R.runtime.sklearn}.</p></div></section>`;
 $('#print-report').onclick=()=>window.print();$('#export-matrix').onclick=()=>download('product-issue-matrix.csv',R.matrix);$('#export-topics').onclick=()=>download('discovered-topics.csv',R.topics.map(t=>({...t,terms:t.terms.join('; '),examples:t.examples.join('; ')})));
}
function navigate(view){if(!['overview','signals','explorer','topics','models','evidence'].includes(view))view='overview';state.view=view;location.hash=view;document.querySelectorAll('nav button').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);b.setAttribute('aria-current',b.dataset.view===view?'page':'false');});({overview,signals,explorer,topics,models,evidence})[view]();window.scrollTo(0,0);}
$('#alert-count').textContent=R.summary.alerts;
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>navigate(b.dataset.view));
$('#close-detail').onclick=()=>$('#detail').close();
window.addEventListener('hashchange',()=>{const view=location.hash.slice(1);if(view!==state.view)navigate(view);});
navigate(location.hash.slice(1)||'overview');
